version: '3.3'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  internet:
  intranet:

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - intranet
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=CRtwmi21
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=a21.cc
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=jgrasiot@gmail.com
      - GF_SMTP_PASSWORD=123123
      - GF_SMTP_FROM_ADDRESS=jgrasiot@gmail.com
    networks:
      - intranet
      - internet
    restart: always
