version: "3.3"

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  internet:
  intranet:

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.1.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host(`prometheus.cryptoscertify.com`)
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.routers.prometheus.tls.certresolver=letsencrypt
      - traefik.http.routers.prometheus.entrypoints=websecure
      - traefik.http.routers.prometheus.middlewares=my-auth
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    networks:
      - intranet
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`monitor.cryptoscertify.com`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=CRtwmi21
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=a21.cc
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=jgrasiot@gmail.com
      - GF_SMTP_PASSWORD=123123
      - GF_SMTP_FROM_ADDRESS=jgrasiot@gmail.com
    networks:
      - intranet
      - internet
    restart: always
  traefik:
    container_name: traefik
    image: traefik:v2.4.9
    restart: always
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --api.dashboard=true
      - --metrics
      - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=jgrasiot@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      # - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`pr1.cryptoscertify.com`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.middlewares=my-auth
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - "traefik.http.middlewares.my-auth.basicauth.users=${AUTH}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik/:/acme/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - intranet
      - internet
