# my global config
global:
  scrape_interval: 120s # By default, scrape targets every 15 seconds.
  evaluation_interval: 120s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "criptoia"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # SYSTEM MONITORING
  - job_name: "prometheus"
    scrape_interval: 120s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: traefik
    scrape_interval: 120s
    static_configs:
      - targets: ["traefik:8080"]

  - job_name: "s2 node exporter"
    scrape_interval: 10m
    static_configs:
      - targets: ["s2.cryptoscertify.com:9100"]
    metrics_path: /metrics

  # MONDES VALORS
  - job_name: "coingeckoproxy s2"
    scrape_interval: 1209965696s
    static_configs:
      - targets: ["51.210.187.61:4000"]
        labels:
          group: "json"
    metrics_path: /req
    params:
      key: ["pJ5dZA8WhAXVaZpJ5d"]
      origen: ["s2"]
      coins:
        [
          "aave,algorand,binancecoin,bitcoin,bitcoin-cash,cardano,chainlink,crypto-dash,curve-dao-token,dogecoin,eos,ethereum,fantom,gochain,internet-computer,iota,kusama,litecoin,matic-network,monero,ocean-protocol,omisego,ontology,polkadot,republic-protocol,seedify-fund,serum,skale,solana,stellar,tether,tezos,the-graph,thorchain,uniswap,zcash"
        ]
  # WALLETS NUMERO TOTAL
  - job_name: "wallet xdai s2"
    scrape_interval: 20m
    static_configs:
      - targets: ["51.210.187.61:3000"]
        labels:
          group: "html"
    metrics_path: /html
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["xdai"]

  - job_name: "wallet bitcoin s2"
    scrape_interval: 20m
    static_configs:
      - targets: ["51.210.187.61:3000"]
        labels:
          group: "json"
    metrics_path: /json
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["bitcoin"]

  - job_name: "wallet ethereum s2"
    scrape_interval: 20m
    static_configs:
      - targets: ["51.210.187.61:3000"]
        labels:
          group: "csv"
    metrics_path: /csv
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["ethereum"]

  - job_name: "wallet binance s2"
    scrape_interval: 20m
    static_configs:
      - targets: ["51.210.187.61:3000"]
        labels:
          group: "csv"
    metrics_path: /csv
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["binance"]

  - job_name: "wallet polygon s2"
    scrape_interval: 20m
    static_configs:
      - targets: ["51.210.187.61:3000"]
        labels:
          group: "csv"
    metrics_path: /csv
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["polygon"]

  # ELASTIC SCRAPPER NEWS
  - job_name: "news count bitcoin s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["bitcoin"]

  - job_name: "news count ethereum s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["ethereum"]

  - job_name: "news count aave s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["aave"]

  - job_name: "news count cardano s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["cardano"]

  - job_name: "news count algorand s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["algorand"]

  - job_name: "news count curve s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["curve-dao-token"]

  - job_name: "news count crypto-dash s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["crypto-dash"]

  - job_name: "news count dogecoin s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["dogecoin"]

  - job_name: "news count eos s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["eos"]

  - job_name: "news count fantom s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["fantom"]

  - job_name: "news count iota s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["iota"]

  - job_name: "news count litecoin s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["litecoin"]

  - job_name: "news count matic-network s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["matic-network"]

  - job_name: "news count monero s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["monero"]

  - job_name: "news count omisego s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["omisego"]

  - job_name: "news count internet-computer s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["internet-computer"]

  - job_name: "news count seedify-fund s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["seedify-fund"]

  - job_name: "news count thorchain s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["thorchain"]

  - job_name: "news count tezos s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["tezos"]

  - job_name: "news count ontology s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["ontology"]

  - job_name: "news count pancakeswap-token s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["pancakeswap-token"]

  - job_name: "news count polkadot s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["polkadot"]

  - job_name: "news count republic-protocol s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["republic-protocol"]

  - job_name: "news count stellar s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["stellar"]

  - job_name: "news count solana s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["solana"]

  - job_name: "news count the-graph s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["the-graph"]

  - job_name: "news count zcash s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["zcash"]

  - job_name: "news count chainlink s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["chainlink"]

  - job_name: "news count gochain s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["gochain"]

  - job_name: "news count kusama s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["kusama"]

  - job_name: "news count serum s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["serum"]

  - job_name: "news count skale s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["skale"]

  - job_name: "news count ocean-protocol s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["ocean-protocol"]

  - job_name: "news count binancecoin s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["binancecoin"]

  - job_name: "news count tether s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["tether"]

  - job_name: "news count uniswap s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["uniswap"]

  - job_name: "news count bitcoin-cash s2"
    scrape_interval: 5m
    static_configs:
      - targets: ["51.210.187.61:3001"]
        labels:
          group: "elastic"
    metrics_path: /news
    params:
      token: ["1venRTb4asd3D3deeddsf"]
      origen: ["s2"]
      target: ["bitcoin-cash"]